name: pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64

    strategy:
      matrix:
        go-version: ['1.18.0']

    steps:
      - uses: actions/checkout@v2
      
      - name: set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
    
      - name: deps
        run: |
          make deps
        
      - name: lint
        run: |
          make lint bin_path=/home/runner/go/bin/

      - name: redis
        run: |
          curl https://raw.githubusercontent.com/abmamo/mkd/main/Makefile --output mkd.mk
          make --makefile="mkd.mk" redis-create redis_port=6399 & 

      - name: test
        run: make test

      - name: build
        run: make build
